Repository cimp08/team-2-frontend, pull requests merged in 2022-06, with the labels that each got.

#87 fix token bugs
  src/pages/Login.js
  src/pages/Swipe.js
Labels: Pull Request

#85 Jest test
  jest-config.js
  package-lock.json
  package.json
  src/App.test.js
  src/__test__/dog.test.js
  src/components/try.js
Labels: Pull Request

#88 Chatt
  .env
  src/components/chat/ChatContainer.js
  src/components/chat/ChatDisplay.js
  src/components/chat/ChatInput.js
  src/components/chat/MatchesDisplay.css
  src/components/chat/MatchesDisplay.js
  src/pages/Chat.js
  src/pages/Swipe.js
Labels: task

#103 fix responsive login/logout button and links in hamburger navbar
  src/components/Header.css
  src/components/Header.js
Labels: Pull Request

#104 fix footer
  package-lock.json
  src/components/Footer.css
  src/components/Footer.js
  src/components/Header.js
  src/components/chat/ChatContainer.css
  src/index.css
  src/pages/Chat.js
  src/pages/Home.css
Labels: Pull Request

#105 fix sideheader links and responsivness
  src/components/SwipeHeader.js
  src/pages/Chat.css
  src/pages/Chat.js
Labels: Pull Request

#107 redesign footer
  src/components/Footer.css
  src/components/Footer.js
  src/pages/Home.js
Labels: Pull Request

#110 delete swipebuttons
  package-lock.json
  src/components/SwipeHeader.js
  src/pages/Swipe.js
Labels: Pull Request

#111 fix #93
  src/components/chat/MatchesDisplay.js
Labels: Pull Request

#114 fix #113
  src/pages/Swipe.css
  src/pages/Swipe.js
Labels: Pull Request

#115 fix footer and scrollbar show at bottom
  src/components/Footer.js
  src/components/chat/ChatDisplay.js
Labels: task

#116 Readme v1
  README.md
Labels: Pull Request

#117 Fix swipe header
  src/components/chat/ChatContainer.css
  src/components/chat/ChatContainer.js
  src/components/chat/ChatDisplay.js
  src/components/chat/ChatInput.js
  src/pages/Chat.js
  src/pages/Swipe.js
Labels: Pull Request

#120 add min height on chatContainer
  src/components/chat/ChatContainer.css
Labels: Pull Request

#122 Cemil
  README.md
  src/components/Footer.css
  src/components/Footer.js
  src/components/Header.css
  src/pages/Profile.css
Labels: Pull Request

#121 make scrollbar on matches display page
  src/components/chat/MatchesDisplay.css
  src/components/chat/MatchesDisplay.js
Labels: enhancement

#124 added eslint and correct all warnings
  .eslintignore
  .eslintrc.json
  package-lock.json
  package.json
  src/App.js
  src/components/Footer.js
  src/components/chat/ChatContainer.js
  src/components/chat/ChatDisplay.js
  src/components/chat/ChatInput.js
  src/components/chat/MatchesDisplay.js
  src/components/try.js
  src/pages/Chat.js
  src/pages/Protected.js
  src/reportWebVitals.js
  src/setupTests.js
Labels: Pull Request

#125 Update testing
  babel.config.js
  jest-config.js
  package-lock.json
  package.json
  src/__test__/dog.test.js
  src/components/chat/ChatInput.js
Labels: Pull Request

#126 Delete a line
  package-lock.json
  src/components/chat/ChatInput.js
Labels: Pull Request

#127 delete shadow from tinder cards
  src/pages/Swipe.css
  src/pages/Swipe.js
Labels: Pull Request

#128 Smallfixes
  package-lock.json
  src/components/Footer.js
  src/components/SwipeHeader.css
  src/components/chat/ChatContainer.css
  src/components/chat/ChatInput.css
  src/components/chat/ChatInput.js
  src/components/chat/MatchesDisplay.js
Labels: Pull Request
